name: main

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    outputs:
      plan-exit-code: "2"
    steps:
      - name: Exit
        run: exit 0

  plan-staging:
    runs-on: ubuntu-latest
    outputs:
      plan-exit-code: "2"
    steps:
      - name: Exit
        run: exit 1

  plan-prod:
    runs-on: ubuntu-latest
    outputs:
      plan-exit-code: "2"
    steps:
      - name: Exit
        run: exit 1

  apply-dev:
    if: |
      github.ref == 'refs/heads/main' &&
      needs.plan-dev.outputs.plan-exit-code == 2
    needs: [plan-dev, plan-staging, plan-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Exit
        run: exit 0

  apply-staging:
    if: |
      github.ref == 'refs/heads/main' &&
      needs.plan-staging.outputs.plan-exit-code == 2 &&

      always() &&
      needs.plan-dev.result == 'success' &&
      needs.plan-staging.result == 'success' &&
      needs.plan-prod.result == 'success' &&
      (needs.apply-dev.result == 'success' || needs.apply-dev.result == 'skipped')
    needs: [apply-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Exit
        run: exit 0

  apply-prod:
    if: |
      github.ref == 'refs/heads/main' &&
      needs.plan-prod.outputs.plan-exit-code == 2 &&

      always() &&
      needs.plan-dev.result == 'success' &&
      needs.plan-staging.result == 'success' &&
      needs.plan-prod.result == 'success' &&
      (needs.apply-dev.result == 'success' || needs.apply-dev.result == 'skipped') &&
      (needs.apply-staging.result == 'success' || needs.apply-staging.result == 'skipped')
    needs: [apply-staging]
    runs-on: ubuntu-latest
    steps:
      - name: Exit
        run: exit 0
